version: '3.9'
services:
  nginx-php:
    image: nginx:alpine
    container_name: nginx-php
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/defalt.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      # - postgres-php
      - mysql-php

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      # - postgres-php
      - mysql-php
  
  #mysql
  mysql-php:
    image: mysql:latest
    container_name: mysql-php
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
  
  #postgres
  # postgres-php:
  #   image: postgres:latest
  #   container_name: postgres-php
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data

